server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlite:/data/social-network.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.community.dialect.SQLiteDialect
  flyway:
    locations: classpath:db/migration/sqlite
  session:
    store-type: jdbc
    timeout: 7d

logging:
  level:
    org.springframework.security: DEBUG

app:
  cors:
    allowed-origin: http://localhost:3000